#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Window Configuration
bspc config border_width          2
bspc config focused_border_color  "#8FBCBB"
bspc config normal_border_color   "#2E3440"
bspc config window_gap            12

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true

bspc config external_rules_command "$HOME/.config/bspwm/external_rules"

# Startup scripts
$HOME/.config/polybar/launch.sh &
picom &
dunst &
