#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

# Window Configuration
bspc config border_width          2
bspc config focused_border_color  "#4084d6"
bspc config normal_border_color   "#000000"
bspc config window_gap            12

bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config gapless_monocle       true

# Workspace assignment
bspc rule -a kitty desktop='^1'
bspc rule -a firefox desktop='^2'
bspc rule -a neovide desktop='^3'
bspc rule -a MuseScore4 desktop='^4'
bspc rule -a libreoffice-startcenter desktop='^5'
bspc rule -a libreoffice-writer desktop='^5'
bspc rule -a libreoffice-calc desktop='^5'
bspc rule -a libreoffice-impress desktop='^5'
bspc rule -a libreoffice-draw desktop='^5'
bspc rule -a libreoffice-math desktop='^5'
bspc rule -a libreoffice-base desktop='^5'

bspc rule -a discord desktop='^7'

# Startup scripts
$HOME/.config/polybar/launch.sh &
feh --bg-fill /usr/share/backgrounds/background.png &
picom &
lxpolkit &
